# Disallowing packages: openvpn
# If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
#addons:
#    apt:
#        sources:
#            - ubuntu-toolchain-r-test
#        packages:
#            - openvpn
sudo: required

env:
  global:
    - BASEIMAGE=project31/docker-openvpn
  matrix:
    - ARCH=x86     FROM=alpine:latest                        IMAGE=$BASEIMAGE:x86_64
    - ARCH=aarch64 FROM=project31/aarch64-alpine-qemu:3.5-7  IMAGE=$BASEIMAGE:aarch64

services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
# prepare qemu
    - if [ $ARCH == 'aarch64' ]; then docker run --rm --privileged multiarch/qemu-user-static:register --reset; fi
    - image="$IMAGE"
    - docker build --build-arg from=$FROM -t "$image" .
    - docker inspect "$image"
    - docker run --rm "$image" openvpn --version || true; # why does it return 1?
    - docker run --rm "$image" openssl version

script:
    - official-images/test/run.sh "$image"
    - test/run.sh "$image"

after_script:
    - docker images

after_success:
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$image"

jobs:
  include:
    - stage: deploy
      script: echo manifest 
