# Disallowing packages: openvpn
# If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
#addons:
#    apt:
#        sources:
#            - ubuntu-toolchain-r-test
#        packages:
#            - openvpn

env:
    - ARCH=x86     DOCKERFILE=Dockerfile         IMAGE=kylemanna/docker-openvpn
    - ARCH=aarch64 DOCKERFILE=Dockerfile.aarch64 IMAGE=project31/aarch64-docker-openvpn

services:
    - docker

before_install:
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
# prepare qemu
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - image="$IMAGE"
    - docker build -f $DOCKERFILE -t "$image" .
    - docker inspect "$image"
    - docker run --rm "$image" openvpn --version || true; fi # why does it return 1?
    - if [ $ARCH == 'x86' ]; then docker run --rm "$image" openssl version; fi

script:
    - if [ $ARCH == 'x86' ]; then official-images/test/run.sh "$image"; fi
    - if [ $ARCH == 'x86' ]; then test/run.sh "$image"; fi

after_script:
    - docker images
