# Disallowing packages: openvpn
# If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
#addons:
#    apt:
#        sources:
#            - ubuntu-toolchain-r-test
#        packages:
#            - openvpn
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -y install docker-ce

env:
    - ARCH=x86     FROM=alpine:latest                       IMAGE=kylemanna/docker-openvpn
    - ARCH=aarch64 FROM=project31/aarch64-alpine-qemu:3.5-7 IMAGE=project31/aarch64-docker-openvpn

services:
    - docker

before_install:
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
# prepare qemu
    - if [ $ARCH == 'aarch64' ]; then docker run --rm --privileged multiarch/qemu-user-static:register --reset; fi
    - image="$IMAGE"
    - docker build --build-arg from=alpine:3.5 -t "$image" .
    - docker inspect "$image"
    - docker run --rm "$image" openvpn --version || true; # why does it return 1?
    - docker run --rm "$image" openssl version

script:
    - official-images/test/run.sh "$image"
    - test/run.sh "$image"

after_script:
    - docker images
